### ISSUE TITLE
Arquivos Javascript

### ISSUE THREAD

**Issue by gegen07** [COLTEC-DAW/Trimestral-1#18]
Pra usar a parte de javascript precisa dar o npm install, não usei o CDN. Como o node_modules tinha mais de 5k de modificações inviabilizou dar o commit na pasta.
Deixei um README.

**Comment by raul4247** [comment]
Você não precisa dar commit no node_modules mesmo não. O package.json tem (ou deveria ter) uma listagem das dependências do projeto. É a melhor opção quando você usa nodejs.

**Comment by gegen07** [comment]
Extamente isso que eu fiz. Deixei um package.json com todas dependências necessárias para rodar o projeto.
